name: Check Code

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    phpcbf-check:
        runs-on: ubuntu-24.04

        strategy:
            matrix:
                php-version: [ '8.2', '8.3', '8.4' ]

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions: mbstring, intl
                    coverage: yes

            -   name: php version
                run: php -v

            -   name: Install Composer dependencies
                run: composer install

            -   name: Run editorconfig check
                run: composer run check:ec

            -   name: Run phpcs
                run: composer run check:phpcs

            -   name: Run phpstan
                run: composer run check:phpstan

            -   name: Run phpunit
                run: composer run check:tests
